### ISSUE TITLE
Correct handling of App termination or backgrounding

### ISSUE THREAD

**Issue by novocodev** [KittyMac/flynn#17]
Are there any examples/documents that show how to correctly handle Application events for backgrounding or termination with Flynn.

Flynn.shutdown() blocks until all actors are complete? 

Looks like this might take longer than the time allowed by the OS to terminate, causing a hard App termination.

I would normally serialise App state and release resources on backgrounding/termination and then recreate new resources from that state on resuming or foregrounding the App again.

I was looking for a way to serialise all actors, and possibly inflight messages, so that the entire actor graph could be restored later and a new scheduler resume processing? Or would this be a bad approach?

**Comment by KittyMac** [comment]
Flynn.shutdown() tells all schedulers that they should terminate when idle, and then it should block until there are no more active schedulers. An active scheduler is one which has actors which are running or waiting to run.  Actors only run or wait to run while they have messages in their message queue.  A behavior call creates a message in said actors queue.

If shutdown() takes a long time to complete, then it could be because your actors are keeping themselves running and never reaching a state to where they are idle (out of messages).  Maybe they're receiving messages on a timer, or behaviors are calling other behaviors.

The scenario to serialize all actors and then shut Flynn down would then be solved by stopping whatever actions are keeping the actors active.  Then creating and calling some kind of beSaveState() method on the actors you want to serialize. Then calling Flynn.shutdown() to block until all actors reach quiescence.

I will set this to be a task to provide an example of actor serialization and Flynn shutdown().  Flynn is getting a major shake up, enough that it will break existing code so the version will move to v0.1.  I want to finish that first, so I will include this example in that.

**Comment by novocodev** [comment]
Thanks for the explanation.

**Comment by KittyMac** [comment]
Flynn v0.1.1 is available. It contains an example showing a Flynn Actor being used as an ObservableObject for SwiftUI, and includes serialization and deserialization.

https://github.com/KittyMac/flynn/tree/master/Examples/ConcurrentDataSwiftUI
