### ISSUE TITLE
Does Flynn support actor references.

### ISSUE THREAD

**Issue by novocodev** [KittyMac/flynn#18]
In some actor models, actors are regularly passed as arguments to other actors, either on creation or in messages.

Usually the actor is not passed directly but it's reference, ID or logical address. This potentially allows actors to be lazy loaded or possibly have messages routed to a actor on a remote host.

It looks like Flynn uses Strong References when passing Actors and Callback Behaviours, causing the entire actor graph to be held in memory on a single host?

Is there a mechanism for using opaque references or addresses with Flynn?

**Comment by KittyMac** [comment]
Classes in Swift are all pass-by-reference and all Flynn Actors are classes.  You can pass references to your actors around, or have multiple references to the same actor. So in the context of a single executable, what you want should already be possible.

Actors being transparently distributed overs networks (actors running on other hosts and/or in other executables) is not supported by Flynn.

Strong references are required to keep Swift from automatically deallocating classes. Flynn should only have strong references to actors where it makes sense; in situations it needs the actor to stay allocated.  This will happen when an actor is scheduled and needs to process its messages.  When an actor finishes processes all waiting messages (and doesn't get rescheduled because more messages arrived in the meantime), then the scheduler's reference to the actor will go away.  If that happens to be the last strong reference to the actor, then the actor will be released from memory.

So, for example, let's say you do this (using the example actor HelloWorld):

```
func foo() {
    HelloWorld().bePrint("hello world")
}
```

When HelloWorld() was created you had a reference to it, and calling bePrint() causes a message to go into the actor's queue and causes that actor to be scheduled.  A flynn scheduler now has a strong reference to the HelloWorld actor, as that actor wants to process the bePrint() message in the future.

It is pretty much guaranteed that this point in the future will be after the current code execution exits the foo() function.  So you reference to the HelloWorld actor will disappear before the bePrint() gets a chance to execute.  if Flynn didn't have a strong reference to HelloWorld, the "hello world" will never print because the actor will go away before it can be executed.

Since the scheduler has a strong reference to HelloWorld, it will get a chance to process its messages and the behavior for bePrint will execute and "hello world" will print.  At that time, the HelloWorld actor will have exhausted its message queue and the scheduler will deschedule it, removing its strong reference to the actor.  Since that is the last strong reference, the HelloWorld actor will then be deallocated.
