### ISSUE TITLE
XCode 14.0.1 build fail

### ISSUE THREAD

**Issue by Kao953** [KittyMac/flynn#23]
error build: Multiple commands produce '/Users/username/Library/Developer/Xcode/DerivedData/funpark-chbiumjcvgfwchdxjhhrhxgpgdju/SourcePackages/plugins/flynn.output/Flynn/FlynnPlugin/FlynnPlugin.swift'

That command depends on command in Target 'Flynn' (project 'Flynn'): script phase “Flynn Plugin - generating behaviours...”

XCode Version 14.0.1 (14A400)
Flynn version 0.4.13
How can I do?

**Comment by KittyMac** [comment]
I have checked on XCode 13.4.1 and XCode 14.1 and I cannot replicate this issue.

You can try any of the following to help provide more information:

- Clean Build Folder and then try building again
- Delete derived data and then try building again
- If your project happens to be a Swift Package Manager project, you can try "swift build" instead of XCode. if it works it might imply something wrong with that specific version of Xcode.
- You can try on XCode 13.4.1 and XCode 14.1 and see if it makes a difference.

If none of the above help, then you will need to provide more information and/or a minimal reproducible project for me to help further.

**Comment by Kao953** [comment]
I confirm 13.4.1 and 14.1(beta) is OK, Thanks.
14.0 and 14.0.1 bad .....
